FROM amazonlinux:2023.1.20230809.0

# dnf fixes tool versions
RUN dnf install -y \
         git \
         sudo \
         make \
         golang.x86_64 \
         postgresql15.x86_64 \
     && rm -rf /var/cache/dnf/* \
     && dnf clean all

# useradd
RUN useradd "dev-user" && echo "dev-user ALL=NOPASSWD: ALL" >> /etc/sudoers
USER dev-user

RUN go install -tags postgres github.com/golang-migrate/migrate/v4/cmd/migrate@v4.17.1