version: "3.8"

services:
  manager:
    build:
      context: .
      dockerfile: Dockerfile.manager
    volumes:
      - ..:/mnt/manager
    working_dir: /mnt/manager
    tty: true
    depends_on:
      - postgres
      - metabase